---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: daily
    groups:
      action-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'build'
  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'build'
