env:
  node: true
  es6: true
  jest: true
extends:
  - standard-with-typescript
  - plugin:jest/recommended
  - plugin:github/recommended
overrides:
  - files: ['*.js', '*.jsx', '*.ts', '*.tsx']
ignorePatterns:
  - '**/dist/*'
  - 'jest.config.js'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
    - './__tests__/tsconfig.json'
plugins:
  - jest
rules:
  'i18n-text/no-en': 'off'
  '@typescript-eslint/space-before-function-paren': 'off'
  'generator-star-spacing': 'off'
