---
name: 'bugalint'
description: 'Convert various linter outputs to standard formats'
inputs:
  inputFile:
    description: 'Path to the file with the linter output'
    required: true
  sarif:
    description: 'Should the action create a SARIF file'
    required: false
    default: 'true'
  comment:
    description: 'Should the action comment on the PR'
    required: false
    default: 'false'
  summary:
    description: 'Should the action create a markdown summary'
    required: false
    default: 'true'
  outputFile:
    description: 'Path to the SARIF file this action will generate'
    required: false
    default: 'sarif.json'
  toolName:
    description: 'Name of the tool to be written in the SARIF'
    required: true
  inputFormat:
    description: 'Name of a known format of the input file'
    required: false
    default: ''
  inputRegex:
    description: 'Regular expression to parse the input file'
    required: false
    default: ''
  levelMap:
    description: 'Mapping from levels in input to SARIF levels (note, warning, error)'
    required: false
    default: ''
  analysisPath:
    description: "The path at which the analysis took place relative to the repository's root. Used to relativize any paths to the repository root path."
    required: false
    default: '.'
  githubToken:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
