name: Lint

on: [pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm clean-install; npm install @microsoft/eslint-formatter-sarif
      - name: Run ESLint
        run: npx eslint . --format @microsoft/eslint-formatter-sarif --output-file lint.sarif
      - name: Print Output
        if: always()
        run: cat lint.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: lint.sarif
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          output: 'lint.txt'
          config: '.mdl.yml'
      - name: Convert
        uses: ./
        if: always()
        with:
          inputFile: 'lint.txt'
          toolName: 'mdl'
          inputFormat: 'mdl'
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: sarif.json
