name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .
        rm -rf build
    - name: Lint
      run: bugalint --lintly
      env:
        LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
